name: "CD (Entrega Contínua): Main Workflow"

env: 
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: [main, a2.2]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Run Deploy
              run: yarn deploy:prod