name: "CD (Entrega Contínua): Main Workflow"

env: 
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: [main, a2.2]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Run Deploy
              run: yarn deploy:prod