name: "CI (Integração Contínua): Main Workflow"

env: 
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    linter:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint
    preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Install Vercel
              run: yarn global add vercel

            - name: Run Preview
              run: yarn deploy:preview