name: "CI (Integração Contínua): Main Workflow"

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    linter:
        run-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint